version: "3.8"

services:
  db:
    image: mysql:5.7.22
    restart: always
    container_name: "django-app-db"
    ports:
      - "32000:3306"
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: Snowboarder
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./server/.dbdata:/var/lib/mysql
    command: --event-scheduler=ON

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./path/to/your/ssl:/etc/ssl:ro
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    command: certonly --staging --cert-name pcn11scert --webroot --webroot-path=/var/www/certbot --email proclubsnation2@gmail.com --agree-tos --no-eff-email --force-renewal -d pcn11smatchmaking.hopto.org
    #command: certonly --staging --cert-name pcn11scert --webroot --webroot-path=/var/www/certbot --email proclubsnation2@gmail.com --agree-tos --no-eff-email --force-renewal -d pcn11smatchmaking.hopto.org

volumes:
  certs:
  webroot:

#     image: nginx:latest
#     volumes:
#       - ./nginx:/etc/nginx/conf.d
#       - certs:/etc/letsencrypt
#     ports:
#       - "80:80"
#       - "443:443"

#   certbot:
#     image: certbot/certbot
#     volumes:
#       - certs:/etc/letsencrypt
#     #command: certonly --cert-name pcn11scert --webroot --webroot-path=/etc/letsencrypt --email proclubsnation2@gmail.com --agree-tos --no-eff-email --force-renewal -d pcn11smatchmaking.hopto.org
#     command: certonly --staging --cert-name pcn11scert --webroot --webroot-path=/etc/letsencrypt --email proclubsnation2@gmail.com --agree-tos --no-eff-email --force-renewal -d pcn11smatchmaking.hopto.org
    
# volumes:
#   certs: