# Generated by Django 3.1.7 on 2023-02-16 04:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='data',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='device_info',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='match_pref',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='open_or_close',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='opponent_found',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='opponent_manager',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='player_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='player_numb',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='player_pref',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='send_v_receive',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='team_league',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='team_name',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
