# Generated by Django 3.1.7 on 2023-02-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230216_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='Unique_Idenitier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.CharField(auto_created=True, db_column='id', db_index=True, db_tablespace='pg_default', editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
