# Generated by Django 3.1.7 on 2023-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230216_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='last_called',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.CharField(auto_created=True, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
