# Generated by Django 3.1.7 on 2023-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230216_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='opponent_found',
            new_name='Opponent_Unique_Idenitier',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='opponent_team',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
