# Generated by Django 3.1.7 on 2023-02-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230216_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='Opponent_Unique_Idenitier',
            new_name='Opponent_Unique_Identifier',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='Unique_Idenitier',
            new_name='Unique_Identifier',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='open_or_close',
            field=models.CharField(default='Open', max_length=255, null=True),
        ),
    ]
