# Generated by Django 3.1.7 on 2023-03-13 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230216_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='SuspendMessageSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
