# Generated by Django 3.1.7 on 2023-03-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mymodel_suspendmessagesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='SuspendMessageSent',
            field=models.DateTimeField(null=True),
        ),
    ]
