# Generated by Django 3.1.7 on 2023-03-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230313_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='last_called',
            field=models.DateTimeField(null=True),
        ),
    ]
