# Generated by Django 3.1.7 on 2023-03-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230314_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='open_or_close',
            field=models.CharField(default='Started', max_length=255),
        ),
    ]
